### ISSUE TITLE
Rayman 3 Crashes when DLL is named d3d8.dll

### ISSUE THREAD

**Issue by RibShark** [ThirteenAG/Ultimate-ASI-Loader#1]
Hello! Thanks for providing this tool. I am having trouble using it with Rayman 3 (which uses DirectX 8). When the DLL is named "dinput8.dll" or "dsound.dll" it works as expected, however when the DLL is named "d3d8.dll", the game crashes. I would quite like to use the integrated d3d8to9 (instead of just using it alongside the ASI Loader, which does work), but with this not working that is not possible

**Comment by ThirteenAG** [comment]
Well, upload an archive with a whole game and send me the link, maybe I'll be able to take a look.

**Comment by RibShark** [comment]
The [demo](http://www.fileplanet.com/119466/110000/fileinfo/Rayman-3-Demo) version of the game exhibits the same bug. With the DLL named d3d8.dll, the game will crash, while with the DLL named dinput8.dll, the game will work (well, it may ask for a CD, but that's better than crashing and can be fixed by changing the compatibility mode to XP).

**Comment by ThirteenAG** [comment]
It seems like the problem might be in the game itself. I'll try to take a look again when I have more time, but it's probably can not be fixed.

**Comment by liaz6212** [comment]
Hi man. It works great even if I rename dll to any name from description, but... I can't force Mod Loader work with your Asi Loader. Can you help me, please?

**Comment by UCyborg** [comment]
It crashes because of #3.
