### ISSUE TITLE
SW: Battlefront 1 (2004)

### ISSUE THREAD

**Issue by DaemonicWar** [ThirteenAG/Ultimate-ASI-Loader#10]
In game black sky-box.
![default](https://user-images.githubusercontent.com/31585531/30001582-c955f2ac-909a-11e7-862b-ed18ff7abe97.jpg)

**Comment by ThirteenAG** [comment]
Meaning what exactly?

**Comment by DaemonicWar** [comment]
Проще будет наверное на русском.
Установил ласт лоадер, решил чекнуть на работу в battlofront-е, все отлично, тестовый скрипт загрузился, но.
В игре черные скайбоксы.
Пробовал старые версии, подменять не dinput8.dll, а другие, проблема осталась.

**Comment by ThirteenAG** [comment]
Странно. Точно wndmode.ini не используется?

**Comment by DaemonicWar** [comment]
Хех, без него скайбокс робит.
Но хотелось что бы игра работала и в окне..
Ладно, благодарю.
Пока и так сойдет, в будущем обойдусь без него. :)

**Comment by ThirteenAG** [comment]
Тогда лучше поискать другой способ получить оконный режим. Исходников нет, пофиксить никак :(
