### ISSUE TITLE
wndmode.ini Issue 

### ISSUE THREAD

**Issue by Alkimical** [ThirteenAG/Ultimate-ASI-Loader#108]
In GTA SA using the wndmode.ini feature got me that white line at the top left when the intro videos are playing. I dont get it in 3 or VC.

![Screenshot (1609)](https://github.com/user-attachments/assets/224d5015-2039-414c-aedd-caa327e12e9e)

**Comment by ThirteenAG** [comment]
It's unsupported legacy feature.

**Comment by Alkimical** [comment]
> It's unsupported legacy feature.

Ok but, is there any way to fix it?
In WidescreenFix.ini setting 16:9 in the `FrontendAspectRatio =` line fix the white line, but the loading bar looks out of sync with the logo (doesn't happen if it's in auto)

![Screenshot (1610)](https://github.com/user-attachments/assets/6e082b16-0b11-4815-9447-88ae443a07fb)
