### ISSUE TITLE
[NFS Undercover] Windowed mode issue

### ISSUE THREAD

**Issue by Keith94** [ThirteenAG/Ultimate-ASI-Loader#11]
This WindowedMode.asi plugin doesn't work with newer versions of UAL (like v4.17): [WindowedMode.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/files/1279105/WindowedMode.zip)

It only works with an older version of UAL (1.13 MB (1,188,864 bytes)) included in the download here: https://nfsmods.ga/mod.php?id=32

Could that be a problem introduced in newer versions?

**Comment by ThirteenAG** [comment]
I don't know, try with ForceEntryPointHook=0.

**Comment by Keith94** [comment]
Yeah, that did the trick. So it's not considered a bug and is more like a feature?

**Comment by ThirteenAG** [comment]
It depends on the game. Different hooking method sometimes fails, but straight up loading from dllmain should work fine. I guess you can say it's a bug, but I don't know if it's fixable. Need to take a look.

**Comment by Keith94** [comment]
Okay, thanks for taking a look.

**Comment by ThirteenAG** [comment]
Provide me with the files maybe, so I could straight up reproduce the problem.

**Comment by Keith94** [comment]
Sure, here's the game files: https://mega.nz/#!WtJx2IzA!kfaaAKVDvsv0fXgLn3kx7y60c_esuDzpeC7ZDsY8Jy8

The plugin links are in my first post.

**Comment by ThirteenAG** [comment]
So, the plugin got to load, it just happened too late. I added a couple of additional kernel32 hooks that get called early upon startup, that should take care of it. If you spot more games with similar problem, let me know.

**Comment by Keith94** [comment]
Nice, that fixed it 👍 For sure I'll let you know if I come across anything else.
