### ISSUE TITLE
CrashDumps for GTAV dinput8.dll

### ISSUE THREAD

**Issue by Michael21107** [ThirteenAG/Ultimate-ASI-Loader#110]
do CrashDumps work for dinput8 in GTAV and in what .ini file can they be disabled, if the `CrashDumps` folder is present?

**Comment by ThirteenAG** [comment]
global.ini or <dllname.ini> alongside dll. Asi loader is universal, I don't see a reason for it to not work with a specific game, unless there's an issue of some kind.

**Comment by Michael21107** [comment]
may i ask what types of crashes would be logged? like, would the _SHV (a .dll library) - some .asi stopped working_  crash be logged?

**Comment by ThirteenAG** [comment]
It's a global exception handler, it generates a crash dump like the one windows does.

**Comment by Michael21107** [comment]
gotcha, thanks
