### ISSUE TITLE
Cannot Start Call of Duty: Black Ops after Installing this.

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [ThirteenAG/Ultimate-ASI-Loader#114]
Sorry to bother you but I met a problem about using this project and may need some help.
I use the DSOUND.DLL, after I copy it to the root directory of the game and start, nothing show up.
No logs and crash reports/dumps, the game process just appears in task manager and then quickly disappeared.
![image](https://github.com/user-attachments/assets/f6e16b0a-4c29-4b21-a04a-aaaa42e49b35)

**Comment by Shiroiame-Kusu** [comment]
After I reviewed README many times, I created the [global.ini](https://github.com/ThirteenAG/Ultimate-ASI-Loader/blob/master/data/scripts/global.ini) just in the game directory.
But the [plugin](https://github.com/xoxor4d/t5-rtx) did not load correctly, and if I change "LoadFromScriptsOnly" to 0, the game boomed.
So I wonder is this problem related to this project or the plugin I used?
[CrashDumps (2).zip](https://github.com/user-attachments/files/16890852/CrashDumps.2.zip)

**Comment by Shiroiame-Kusu** [comment]
I found that it was my problem, sorry about this. :(

**Comment by ThirteenAG** [comment]
What was it? Crash dump indicates a crash inside exe, not asi loader. Generally putting asi loader without plugins into game directory shouldn't cause crashes.
