### ISSUE TITLE
New Starfield Shattered Space crashes on load with this enabled

### ISSUE THREAD

**Issue by ZeeOgre** [ThirteenAG/Ultimate-ASI-Loader#121]
While it does not appear bink64 was updated, when I have this enabled the game CTD

**Comment by ThirteenAG** [comment]
Did you remove all asi plugins? Why not post a crash dump?

**Comment by ZeeOgre** [comment]
didn't see a dump.. interesting.. will re-enable with no ASI plugins, and then re-enable those one at a time (only have two! :))

**Comment by ZeeOgre** [comment]
Appears it was FTTU -- will reach out to mod author -- BetterConsole still working as expected.
Thanks as always for the AMAZING quick reply!

**Comment by ThirteenAG** [comment]
Okay, no problem.
