### ISSUE TITLE
Can't compile, have missing files

### ISSUE THREAD

**Issue by imedox** [ThirteenAG/Ultimate-ASI-Loader#134]
Hi,
first thank you for your free hard work, i try to compile the x64 version get error missing file "FunctionHookMinHook", "MinHook"...
can you pls update the repo to have all file required for build without errors.
thanks you.

**Comment by ThirteenAG** [comment]
All files are present, two CI versions are able to compile it just fine.

**Comment by imedox** [comment]
you right im sorry, i clone the rep before that why got errors.
