### ISSUE TITLE
Not working in Wine with override mode on Native, or Native/Built-in.

### ISSUE THREAD

**Issue by bloodshinoda** [ThirteenAG/Ultimate-ASI-Loader#15]
Wine (from 1.1.21 to 1.7.55) doesn't load dinput8.dll even with the proper override mode (native) selected.

#**LastRunWine.log**

wine: cannot find L"C:\\windows\\system32\\plugplay.exe"
err:winedevice:ServiceMain driver L"WineBus" failed to load
trace:x11settings:X11DRV_Settings_SetHandlers Resolution settings now handled by: NoRes
trace:x11settings:X11DRV_Settings_SetHandlers Initialized new display modes array
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 0: 1920x1080x32 @60 Hz (NoRes)
trace:x11settings:X11DRV_Settings_SetHandlers Resolution settings now handled by: NoRes
trace:x11settings:X11DRV_Settings_SetHandlers Initialized new display modes array
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 0: 1920x1080x32 @60 Hz (NoRes)
trace:x11settings:X11DRV_Settings_SetHandlers Resolution settings now handled by: XRandR
trace:x11settings:X11DRV_Settings_SetHandlers Destroying old display modes array
trace:x11settings:X11DRV_Settings_SetHandlers Initialized new display modes array
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 0: 1920x1080x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 1: 1920x1080x32 @2 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 2: 640x480x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 3: 800x600x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 4: 1024x768x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 5: 1280x1024x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 6: 1280x720x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 7: 1344x756x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 8: 1600x900x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 9: 1680x1050x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 10: 1920x1058x32 @1 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 11: 1920x1080x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 12: 1920x1080x8 @2 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 13: 640x480x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 14: 800x600x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 15: 1024x768x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 16: 1280x1024x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 17: 1280x720x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 18: 1344x756x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 19: 1600x900x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 20: 1680x1050x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 21: 1920x1058x8 @1 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 22: 1920x1080x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 23: 1920x1080x16 @2 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 24: 640x480x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 25: 800x600x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 26: 1024x768x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 27: 1280x1024x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 28: 1280x720x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 29: 1344x756x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 30: 1600x900x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 31: 1680x1050x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 32: 1920x1058x16 @1 Hz (XRandR)
trace:x11settings:X11DRV_Settings_SetHandlers Resolution settings now handled by: XRandR
trace:x11settings:X11DRV_Settings_SetHandlers Destroying old display modes array
trace:x11settings:X11DRV_Settings_SetHandlers Initialized new display modes array
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 0: 1920x1080x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 1: 1920x1080x32 @2 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 2: 640x480x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 3: 800x600x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 4: 1024x768x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 5: 1280x1024x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 6: 1280x720x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 7: 1344x756x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 8: 1600x900x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 9: 1680x1050x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 10: 1920x1058x32 @1 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 11: 1920x1080x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 12: 1920x1080x8 @2 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 13: 640x480x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 14: 800x600x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 15: 1024x768x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 16: 1280x1024x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 17: 1280x720x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 18: 1344x756x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 19: 1600x900x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 20: 1680x1050x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 21: 1920x1058x8 @1 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 22: 1920x1080x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 23: 1920x1080x16 @2 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 24: 640x480x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 25: 800x600x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 26: 1024x768x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 27: 1280x1024x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 28: 1280x720x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 29: 1344x756x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 30: 1600x900x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 31: 1680x1050x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 32: 1920x1058x16 @1 Hz (XRandR)
err:module:import_dll Library d3dx9_43.dll (which is needed by L"C:\\gtavc\\d3d8.dll") not found
trace:x11settings:X11DRV_Settings_SetHandlers Resolution settings now handled by: NoRes
trace:x11settings:X11DRV_Settings_SetHandlers Initialized new display modes array
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 0: 1920x1080x32 @60 Hz (NoRes)
trace:x11settings:X11DRV_Settings_SetHandlers Resolution settings now handled by: XRandR
trace:x11settings:X11DRV_Settings_SetHandlers Destroying old display modes array
trace:x11settings:X11DRV_Settings_SetHandlers Initialized new display modes array
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 0: 1920x1080x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 1: 1920x1080x32 @2 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 2: 640x480x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 3: 800x600x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 4: 1024x768x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 5: 1280x1024x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 6: 1280x720x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 7: 1344x756x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 8: 1600x900x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 9: 1680x1050x32 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 10: 1920x1058x32 @1 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 11: 1920x1080x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 12: 1920x1080x8 @2 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 13: 640x480x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 14: 800x600x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 15: 1024x768x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 16: 1280x1024x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 17: 1280x720x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 18: 1344x756x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 19: 1600x900x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 20: 1680x1050x8 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 21: 1920x1058x8 @1 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 22: 1920x1080x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 23: 1920x1080x16 @2 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 24: 640x480x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 25: 800x600x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 26: 1024x768x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 27: 1280x1024x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 28: 1280x720x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 29: 1344x756x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 30: 1600x900x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 31: 1680x1050x16 @60 Hz (XRandR)
trace:x11settings:X11DRV_Settings_AddOneMode initialized mode 32: 1920x1058x16 @1 Hz (XRandR)
err:menubuilder:wWinMain unknown option L"-r"
err:module:attach_process_dlls "dinput8.dll" failed to initialize, aborting
err:module:LdrInitializeThunk Main exe initialization for L"C:\\gtavc\\gta-vc.exe" failed, status c0000005

#**LastRunX11.log**

WineskinX11: main(): argc=10
Waiting for startup parameters via Mach IPC.
WineskinX11: do_start_x11_server(): argc=10
Attempting to use pixel depth of 24
[2214366.008] WineskinX11 starting:
[2214366.009] X.Org X Server 1.13.0
[2214366.009] Build Date: 20120921
[2214366.009] _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
[2214366.012] Initializing built-in extension Generic Event Extension
[2214366.012] Initializing built-in extension SHAPE
[2214366.012] Initializing built-in extension MIT-SHM
[2214366.012] Initializing built-in extension XInputExtension
[2214366.012] Initializing built-in extension XTEST
[2214366.012] Initializing built-in extension BIG-REQUESTS
[2214366.012] Initializing built-in extension SYNC
[2214366.012] Initializing built-in extension XKEYBOARD
[2214366.012] Initializing built-in extension XC-MISC
[2214366.012] Initializing built-in extension XINERAMA
[2214366.012] Initializing built-in extension PseudoramiX
[2214366.012] Initializing built-in extension XFIXES
[2214366.012] Initializing built-in extension RENDER
[2214366.012] Initializing built-in extension RANDR
[2214366.012] Initializing built-in extension DAMAGE
[2214366.012] Initializing built-in extension MIT-SCREEN-SAVER
[2214366.012] Initializing built-in extension DOUBLE-BUFFER
[2214366.012] Initializing built-in extension RECORD
[2214366.012] Initializing built-in extension X-Resource
[2214366.012] Initializing built-in extension XVideo
[2214366.012] Initializing built-in extension XVideo-MotionCompensation
[2214366.012] Initializing built-in extension GLX
[2214366.012] x: 0, y: 0, w: 1920, h: 1058
[2214366.054] (II) GLX: Initialized Core OpenGL GL provider for screen 0
[2214366.055] [dix] Could not init font path element /Users/ibloodheuer/Applications/Wineskin/GTA Vice City.app/Contents/Frameworks/bin/fonts/75dpi, removing from list!
[2214366.055] [dix] Could not init font path element /Users/ibloodheuer/Applications/Wineskin/GTA Vice City.app/Contents/Frameworks/bin/fonts/100dpi, removing from list!
[2214366.055] [dix] Could not init font path element /Users/ibloodheuer/Applications/Wineskin/GTA Vice City.app/Contents/Frameworks/bin/fonts/cyrillic, removing from list!
[2214366.055] [dix] Could not init font path element /Users/ibloodheuer/Applications/Wineskin/GTA Vice City.app/Contents/Frameworks/bin/fonts/misc, removing from list!
[2214366.055] [dix] Could not init font path element /Users/ibloodheuer/Applications/Wineskin/GTA Vice City.app/Contents/Frameworks/bin/fonts/OTF, removing from list!
[2214366.055] [dix] Could not init font path element /Users/ibloodheuer/Applications/Wineskin/GTA Vice City.app/Contents/Frameworks/bin/fonts/Speedo, removing from list!
[2214366.055] [dix] Could not init font path element /Users/ibloodheuer/Applications/Wineskin/GTA Vice City.app/Contents/Frameworks/bin/fonts/TTF, removing from list!
[2214366.055] [dix] Could not init font path element /Users/ibloodheuer/Applications/Wineskin/GTA Vice City.app/Contents/Frameworks/bin/fonts/Type1, removing from list!
[2214366.056] [dix] Could not init font path element /Users/ibloodheuer/Applications/Wineskin/GTA Vice City.app/Contents/Frameworks/bin/fonts/util, removing from list!
[2214368.477] x: 0, y: 0, w: 1920, h: 1080
Hardware:

    Hardware Overview:

      Model Name: iMac
      Model Identifier: iMac10,1
      Processor Name: Intel Core 2 Duo
      Processor Speed: 3,06 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache: 3 MB
      Memory: 8 GB
      Bus Speed: 1,07 GHz
      Boot ROM Version: IM101.00CF.B00
      SMC Version (system): 1.52f9

Graphics/Displays:

    NVIDIA GeForce 9400:

      Chipset Model: NVIDIA GeForce 9400
      Type: GPU
      Bus: PCI
      VRAM (Total): 256 MB
      Vendor: NVIDIA (0x10de)
      Device ID: 0x0869
      Revision ID: 0x00b1
      ROM Revision: 3454
      Displays:
        iMac:
          Display Type: LCD
          Resolution: 1920 x 1080
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Automatically Adjust Brightness: No

**Comment by ThirteenAG** [comment]
I can't help you with that. Doesn't seem like you have a specific problem with the loader though.

>>err:module:import_dll Library d3dx9_43.dll (which is needed by L"C:\gtavc\d3d8.dll") not found
