### ISSUE TITLE
d3d8to9 update

### ISSUE THREAD

**Issue by AeroWidescreen** [ThirteenAG/Ultimate-ASI-Loader#18]
https://github.com/elishacloud/dxwrapper/issues/9#issuecomment-386767247

https://github.com/crosire/d3d8to9/commit/100f6b51d0a3e9bf3145da0ac7a65a5e18ba8f75

I'm assuming what elishacloud really wants is for you to update UAL with the latest changes that d3d8to9 has.

**Comment by ThirteenAG** [comment]
Will do tomorrow.
