### ISSUE TITLE
Line breaks in wndmode.ini

### ISSUE THREAD

**Issue by Keith94** [ThirteenAG/Ultimate-ASI-Loader#2]
Just a minor thing that I noticed, when using wndmode.ini feature of ASI Loader, each setting in wndmode.ini has line breaks after it making it 2x taller... I compared it to the [original(?) wndmode](https://bitbucket.org/veg/tinyddraw/downloads) and it doesn't have the same thing, which seems odd.

**Comment by ThirteenAG** [comment]
Well, I know about this, but the original file is fine: https://github.com/ThirteenAG/Ultimate-ASI-Loader/blob/master/UALx86/wndmode.ini
Not sure at what point it breaks.

**Comment by Keith94** [comment]
That's strange.. hope you figure it out sometime.
