### ISSUE TITLE
Issue with GTASA Control Center

### ISSUE THREAD

**Issue by P2FX** [ThirteenAG/Ultimate-ASI-Loader#20]
This ASI loader does not work well with GTASA Control Center. Weapon info\player stats\girlfriend stats\time of day\clock speed\game speed all read zero with this ASI loader installed. Everything works flawlessly with Silent's ASI loader. Just something you may wanna know.

**Comment by ThirteenAG** [comment]
No idea how it would affect the external program, perhaps try this alternative: http://hotmist.ddo.jp/tool/same/index.html
