### ISSUE TITLE
Ultimate-ASI-Loader x86 source

### ISSUE THREAD

**Issue by SaifKhaan** [ThirteenAG/Ultimate-ASI-Loader#28]
Hi
i just wanna load ''scripts'' folder from C: then i changed path and compiled successfuly for x64
https://ibb.co/TmTGyfL

and the same i did in x86 source but getting errors
https://ibb.co/5xQSp2y
https://ibb.co/vZvZ1s1
sorry i'm noob zero knowledge in programming can u please help me to fix errors in x86 source. btw these are default errors in your source that you gave for x86

**Comment by ThirteenAG** [comment]
You need to clone the repo recursively with submodules and dxsdk for x86 version. 
Appveyor can compile that source, that means anyone else can.

**Comment by SaifKhaan** [comment]
Thanks for your reply
MemoryModule.h and d3d8to9.hpp aren't present in your source where can i get thsese files are required

**Comment by ThirteenAG** [comment]
Everything is present.
https://github.blog/2016-02-01-working-with-submodules/

**Comment by SaifKhaan** [comment]
reason i was getting errors because i downloaded source .zip file from https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases
and in this zip source "external/MemoryModule.h/.c" and "external/d3d8.cpp/.h" are missing
and now problem has been solved i directly loaded in vs2019 via github extension
thanks and atlast i wanna ask 
will it work in .dll injecting method?
i tried injecting dinput8.dll/asi-loader using "Extreme injector Tool" but not working

**Comment by ThirteenAG** [comment]
This is the dll injecting method, why would you do that I have no idea.

**Comment by SaifKhaan** [comment]
actually anti cheat servers are detecting .asi/.dll files in gta directory after changing path of loading scripts/.asiMods to C drive now im getting kick from anticheat for placing dinput8.dll in gta directory the only way in my opinion to bypass anticheat is directly inject dinput8.dll which is asi loader to gameprocess .exe and then that injected dll will load any kind of asi mods from C:\scripts  
will be thankful to you if u can help me to make it work in injection method. :-)

**Comment by ThirteenAG** [comment]
>actually anti cheat servers are detecting .asi/.dll files in gta directory after changing path of loading scripts/.asi

And rightfully so.
