### ISSUE TITLE
GTA:SA crashes when trying to set the game's gravity using plugin-sdk

### ISSUE THREAD

**Issue by Lordmau5** [ThirteenAG/Ultimate-ASI-Loader#29]
Hey there!

So I've been informed about this ASI Loader being a **MUCH MORE** improved version over Silent's ASI Loader (I'm unsure if it's written from the ground up or something?)

Anyway, onto the problem:
I'm writing a GTA:SA Chaos Mod using the plugin-sdk (which means I'll also look into supporting Vice City and III later on as they share roughly the same code base) and told a few friends of mine to switch over to this ASI Loader as it contains a crash dumper.
The crash dumper is useful because, as we all know, the people at Rockstar weren't the sharpest tools in the shed at the time they made these games so they have a chance of crashing - either on their own or due to certain things they would never have expected to happen (especially with a Chaos Mod that messes with the gameplay a lot)

Now, when I try to set the game's gravity with the plugin-sdk, it works perfectly fine with Silent's ASI Loader.

With this one? - It crashes.

Attached are the log and the `.dmp` file in a ZIP archive.
[gravity_crash.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/files/3484700/gravity_crash.zip)

I'm really hoping this is just an oversight that can be easily fixed - Right off the bat I don't see why it *shouldn't* be possible to fix this, seeing as it works fine in Silent's ASI Loader.

**Comment by ThirteenAG** [comment]
There's is nothing to fix in the asi loader, it only loads what you provide. If you load the asi that crashes, it's your code that crashes and it's up to you to fix it.

**Comment by Lordmau5** [comment]
There was a different version of Silent's ASI Loader that also made the game crash when changing the gravity.

Why would it work with a specific version of Silent's ASI loader and not with your's / another version of his ASI loader?

**Comment by ThirteenAG** [comment]
How can I tell without looking at the code? Most likely you're doing something wrong.

**Comment by Lordmau5** [comment]
I'm not denying potentially doing something wrong, it's just... super weird to me.

The code can be found here:
https://github.com/gta-sa-chaos-mod/ASI-script
(For the Gravity effect, it's here: https://github.com/gta-sa-chaos-mod/ASI-script/blob/master/Gravity.cpp)

I'm gonna look into my script with a debugger later in combination with an attached .pdb file to see what is *actually* causing it. Or rather, which parts in my code are causing it to crash.

I'll report back once I'm done with that :)

**Comment by ThirteenAG** [comment]
Generally I would say you're overwriting a memory region without doing virtual protect somewhere. Some versions of asi loader unprotect the entire exe before loading plugins, but you shouldn't rely on that. Or do unprotect on your own. There's a demo plugin on appveyor that does it, maybe if you install that, it won't crash and confirm my theory.

**Comment by Lordmau5** [comment]
Using the `ExeUnprotect.asi` script from AppVeyor does indeed make it work.

I've managed to get it working now by unprotecting the `GAME_GRAVITY` address from within my effect, thank you for this tip :D

Seems like Silent's ASI Loader *was* unprotecting the whole executable in that case, huh

**Comment by ThirteenAG** [comment]
Yes, there's a reason why it does that in the source code(some cleo4 crash fix). But designing plugins that rely on a specific asi loader feature is a bad idea, so ual doesn't do unprotect(except if loaded as xlive.dll).

**Comment by Lordmau5** [comment]
I wasn't actually aware of the unprotected vs. protected memory part - I just... assumed it could've been something that was working in his over your code.

I'm happy I know about this now though, that means I have finer control over the memory sections I'm unprotecting (in this case, right now, only the gravity value, as all others were fine in the past from what I remember) :)
