### ISSUE TITLE
Return Windows XP compatibility

### ISSUE THREAD

**Issue by Psycho-A** [ThirteenAG/Ultimate-ASI-Loader#30]
Older versions of ASI Loader had Windows XP support, while newer not. Why? Updates for updates? It's designed for old-school games, so it's logical to have support their native OS. Also, ASI Loader mostly doesn't increase system requirements, so it's not bad to play old games on some old system or laptop, and have all ASI patches which mainly works good on Windows XP.

**Comment by ThirteenAG** [comment]
Because I want to play games using modern operating systems, and I'm making my fixes using modern tools. I couldn't care less if it's compatible with windows xp, that is not a problem for me and never will be in the future, so I'm not making any effort to solve it.

**Comment by Psycho-A** [comment]
You want to say you're making your fixes for yourself in first turn, not for users?
I don't mind what's the problem to play games on modern OSes if Loader will have backward compatibility - all previous Loader versions runs just fine on Windows 7-10. I don't know about tools you're using, but even the VS2017 have Windows XP-compatible compiling mode.

**Comment by road24** [comment]
It's Open source, fork and make the patch if you want it badly and want to support community, if You agree with the project submit the patch , if don't mantain ir as a separate project

**Comment by ThirteenAG** [comment]
It's like I said, windows xp compatibility is not the problem I want to solve in my free time, and whilst this project may work under xp with certain compiler switches, some plugins in WFP will not, because of the usage of Vista+ APIs.

**Comment by cesar300** [comment]
Hello.
Have you tried this?
https://github.com/tumagonx/XomPie
1 - Install it on Windows XP 32 bit (64 bit not tested).
2 - Right click on asi loader and send to xpatcher.
3 - Press enter and select only (IMPORTANT) the 7th option pressing 7 in the aplhanumeric keyboard. (shell32.dll).
4 - Press enter and let the program make us a favour. Automatically makes a backup of the original file (example d3d8.bak) if you want to restore it.
5 - If any problem occurs, install vcredist 2013 and/or 2015.
Thanks and enjoy gaming on Windows XP.

**Comment by xan1242** [comment]
Anybody still looking for an XP fix, check out the fork I made for my NFSHP2 fix, should work on other games too.
It's actually quite simple and doesn't break compatibility with newer Windows OS'.
Just replaced the function SHGetKnownFolderPath with its older variant SHGetFolderPath to get it working.

[Ultimate ASI Loader Windows XP Edition](https://github.com/xan1242/Ultimate-ASI-Loader)

**Comment by PentiumMMX166** [comment]
Xompie is a virus, avast detected it as Win32:Malware-gen

**Comment by Kirito03** [comment]
PentiumMMX166, are you bloody kidding us? Malware, to put it simple, some ad is a virus? And you using Avast? All I can recommend to you: delete github account, format system partion and never ever install avast again! (sorry, pals, for such an off-top, but...)

**Comment by Epictyphlosion** [comment]
@xan1242 Doesn't work with NFSU2 widescreen patch. I get the following error: `The procedure entry point GetFileInformationByHandleEx could not be located in the dynamic link library KERNEL32.dll.` Using XomPie with option 7 selected doesn't fix this either.

Also, why are issues on your repository disabled?

**Comment by xan1242** [comment]
> Also, why are issues on your repository disabled?

Because it's a fork. Forks cannot have issues enabled.

> Doesn't work with NFSU2 widescreen patch. I get the following error:

That's the fault of the WS fix moreso than the ASI loader itself. If you'd remove the WS fix, it would probably load just fine. ASI loader does start up even without scripts in the folder, so if the game starts without any ASI files, it's the ASI and not the loader that causes the problem.

That being said, I can't resolve that for you at the moment, only @ThirteenAG can and it's very unlikely that he's interested in doing so. The only thing I could suggest is to try using an older version of the WS fix to see if that would avoid that function call. (Probably not, I assume it fails on loading the .dat file, which is probably fixable with an older Win32 call).

**Comment by Epictyphlosion** [comment]
> The only thing I could suggest is to try using an older version of the WS fix to see if that would avoid that function call.

I don't think older versions are hosted? I'll have to check.

**Comment by xan1242** [comment]
[nfsu2ws.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/files/9078277/nfsu2ws.zip)

Here you go, a version from December 2018. It doesn't seem to contain an import of GetFileInformationByHandleEx so it should theoretically work out for you.

**Comment by classc7601** [comment]
This is what I think about the miserable author that ignores poor people:
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/96195759/55cb107b-7666-4699-8ee5-80544795de20)

**Comment by regeditedit2012** [comment]
@xan1242 Doesn't work with GTA Vice City First Person View mod. I get  Unhandled Exception: c0000005
                                                                                                                At address: 02fa6ba0
