### ISSUE TITLE
After putting dinput8 in GTAIVCE root directory and launching the game... the game doesn't even launch. Nothing appears. It just closes.

### ISSUE THREAD

**Issue by nejby** [ThirteenAG/Ultimate-ASI-Loader#31]

**Comment by nejby** [comment]
replacing with bink32w doesn't work. It's just crashing game and nothing appears on screen/
naming it as (for example) d3d8.dll doesn't read at all

**Comment by ThirteenAG** [comment]
I can't do anything because it works for me. At least I need to take a look at crash dump that you should provide.

**Comment by nejby** [comment]
[launcher.log](https://github.com/ThirteenAG/Ultimate-ASI-Loader/files/4399072/launcher.log)
i found this crash dump (i guess) in Documents\Rockstar Games\Launcher

**Comment by ThirteenAG** [comment]
That is not a crash dump
http://dk22pac.blogspot.com/2013/02/how-to-enable-crash-dumps-dmp-files.html

**Comment by nejby** [comment]
https://drive.google.com/drive/folders/1HXVhAPUFV9g_Z2PfUL-fWfwkZfOfUkcr?usp=sharing
ok i am sending these gtaiv crash dumps here

**Comment by ThirteenAG** [comment]
And why are you blaming asi loader when you installed plugins that are incompatible with this game version? IVLodLights.asi crashes for you.

**Comment by nejby** [comment]
Oh. Sorry for bothering you. Closing this issue.
