### ISSUE TITLE
GTAIV 1.2.0.32 support?

### ISSUE THREAD

**Issue by usuarionuevor** [ThirteenAG/Ultimate-ASI-Loader#32]
Can you add support for latest Steam version of GTAIV: The Complete Edition please?

**Comment by ThirteenAG** [comment]
It supports any game.

**Comment by usuarionuevor** [comment]
Sjaak's Trainer doesn't load

**Comment by ThirteenAG** [comment]
So? What does it have to do with asi loader?

**Comment by usuarionuevor** [comment]
it seems none of the old scripthook plugins works, I also tried to compile myself from Aru's source and also error, so far only your own plugins works, is there any template to build plugins compatible with this loader? (your src are not complete)

**Comment by usuarionuevor** [comment]
@ThirteenAG I found injector content by thelink2012 https://github.com/thelink2012/injector
but I can't find the rest... is there any chance to have sort of a template like old Aru's source in order to build .asi mods for latest version of the game, please?
