### ISSUE TITLE
Can't load saves in GTA IV

### ISSUE THREAD

**Issue by NikoBellicIV** [ThirteenAG/Ultimate-ASI-Loader#36]
I can't load any saved games in GTA IV when using this .dll.  
Running windows 10, GTA IV Complete Edition from Steam.
  It was working fine until recently.  
What happens is the game starts loading but then the message onscreen changes from "Loading, please wait" to some thing like "Unable to load savegame. Starting new game..." and then it starts a new game.  If I then create a new save I can't load the new saves either. 
Problem starts occurring before I install any plugins.  Just the ASI-Loader dinput8.dll file.
  If I delete the .dll the problem goes away. 
I tried renaming the dll to dinput.dll or dsound.dll but the problem persisted.
I created a CrashDumps folder but no crash dump was created.

**Comment by c0ap** [comment]
Also have the same issue. Doesn't happen at all if I delete the .dll.

Also have an issue where the game won't launch at all if I have any kind of DX9 to VK/DX11 wrapper together with the .dll and haven't managed to find a solution.

**Comment by NikoBellicIV** [comment]
version 4.57 seems to be working.  Thank you!
