### ISSUE TITLE
Direct3D8DisableMaximizedWindowedModeShim option shouldn't use system path to d3d8.dll

### ISSUE THREAD

**Issue by UCyborg** [ThirteenAG/Ultimate-ASI-Loader#4]
If it's enabled and user wants to use dgVoodoo Direct3D8 -> 11 wrapper, it can happen that dgVoodoo will not be loaded because in the else branch you're using path to system d3d8.dll in LoadLibrary, while you should use just "d3d8.dll" because mere fact that you're in the else branch tells you you're not a d3d8.dll proxy so whatever d3d8.dll comes first can be used. This way the option behaves properly in both scenarios. I've noticed this with Max Payne 2. You need this patch for it to work with dgVoodoo at all: http://www.vogons.org/viewtopic.php?f=8&t=51579

**Comment by UCyborg** [comment]
It also seems renaming ASI loader to msacm32.dll for both Max Payne games ensures out-of-the box compatibility with dgVoodoo for those games.

**Comment by ThirteenAG** [comment]
Regarding both issues you mentioned, can you test this version?
https://transfer.sh/y6PVr/dinput8.dll

If it's all good, I'll commit the changes.

**Comment by UCyborg** [comment]
New DLL works great! I haven't noticed anything out of the ordinary. Rayman 3 works as well, although it crashes if d3d8to9 is used and the game is minimized, but that seems to be d3d8to9 wrapper bug, not ASI loader bug. Direct3D8DisableMaximizedWindowedModeShim fixes the crash that occurs with stock d3d8 after the intro plays, it also seems to work with properly with dgVoodoo as well.

**Comment by ThirteenAG** [comment]
Great, thanks.

**Comment by UCyborg** [comment]
Actually, winmmbase.dll name works only for Max Payne 2, at least here, I said it could be renamed winmmbase.dll for dgVoodoo, but on the other hand, probably better be left as it is (I'm talking about widescreen fixes). If someone knows how to install dgVoodoo, he can probably test the name that works for ASI loader as well, as it seems things don't behave consistently across systems. Someone at http://www.vogons.org/viewtopic.php?f=9&t=34931&start=2840 said msacm32.dll worked for him until he tried ReShade and then he had to rename it to winmmbase.dll

**Comment by ThirteenAG** [comment]
winmmbase.dll is not very reliable. I don't think it's ever loaded on win7, probably only newer systems use it for something.
