### ISSUE TITLE
Cannot load ASI files if the exe is encrypted with SteamStub or Origin

### ISSUE THREAD

**Issue by WinterNya** [ThirteenAG/Ultimate-ASI-Loader#44]
If the game exe is encrypted with SteamStub (some Steam games) or Origin (all Origin games), ASI Loader does not load any ASI files. After decrypting the exe using external tools and running it decrypted, ASI Loader works fine. Is there a possibility to make the loader work on encrypted exes?

**Comment by ThirteenAG** [comment]
Worked fine so far for everyone who used it to load plugins in these games.

**Comment by anadius** [comment]
Tried testing it with The Sims 4 on Origin.

Made a 64-bit `.dll`, basically just this:
```cpp
BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    if (ul_reason_for_call == DLL_PROCESS_ATTACH)
    {
        MessageBoxA(NULL, "attach!", "title", MB_ICONINFORMATION | MB_OK);
    }
    return TRUE;
}
```
Tried adding Ultimate ASI Loader as `dinput8.dll`, `dsound.dll` (the game crashed), `version.dll` and `wininet.dll`. It didn't show my message box. It didn't matter if I started the game from the exe with or without Origin running, or from Origin - the result was the same.

Then, for the sake of testing, I tried with the cracked exe. I put the renamed cracked exe in the same folder - so everything is the same, it's just the exe that differs. And this time it worked fine 3/4 times. `dinput8.dll` didn't show my message but `dsound.dll`, `version.dll` and `wininet.dll` worked flawlessly.

I tried my `.dll` with another loader and it worked fine with the legit game - but it's not open source and the author doesn't like when people use it in their projects.

**Comment by ThirteenAG** [comment]
Hm, 64 bit UAL is not commonly used by me, so I have no idea. Maybe you should try using ini file and set this parameter to 0:
https://github.com/ThirteenAG/Ultimate-ASI-Loader/blob/master/data/scripts/global.ini#L4
See what happens then.

**Comment by anadius** [comment]
Okay, I made a `global.ini` with just
```ini
[GlobalSets]
DontLoadFromDllMain=0
```
and it seems to work with The Sims 4!

**Comment by WinterNya** [comment]
The above also fixes my issues with SteamStub-protected games (or at least the ones that I tested and didn't work). Thanks!

**Comment by ThirteenAG** [comment]
I see, the default asi loading method is preferable, but DRM is DRM, it can mess things up. So this option is for the rescue, or some debugging is needed to make the code account for DRM shenanigans. Perhaps it is something to mention in the readme,
