### ISSUE TITLE
d3d12 and bink

### ISSUE THREAD

**Issue by imedox** [ThirteenAG/Ultimate-ASI-Loader#46]
awesome job you do, pls Can you add d3d12 and binkw64, got game run only on it ❤ (^_^)

**Comment by ThirteenAG** [comment]
And what game is that?

**Comment by imedox** [comment]
Cyberpunk 2077 and all next gme Far Cry 6...ther is many of them like run in only dx12

**Comment by ThirteenAG** [comment]
Added in latest version.
