### ISSUE TITLE
Please create a separate release for SA: Definitive Edition

### ISSUE THREAD

**Issue by x87** [ThirteenAG/Ultimate-ASI-Loader#50]
Many people are confused by steps needed for installing ASI loader. Some of them mix the 32-bit and 64-bit, some miss the rename part. If possible, can we create a standalone release tag for GTA SA: DE (and potentially other games in the remaster) where:

1. it has only 64-bit version
2. dinput8.dll renamed to version.dll

so that mod authors can link to that specific tag?

If not possible within the current repo, what would be the best course of actions to create another repo with the same?

Thanks!

**Comment by ThirteenAG** [comment]
Hmm, let me think about it, I'll try to come up with some solution.

**Comment by thethiny** [comment]
@x87 can't you just fork it and do the release? I mean if someone doesn't know how to rename a dll then he's not gonna now how to use a mod. Sounds like their problem to me.

**Comment by ThirteenAG** [comment]
https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/tag/Win32-latest
https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/tag/x64-latest
