### ISSUE TITLE
Can this work on F1 Challenge 99-02 or rFactor 1?

### ISSUE THREAD

**Issue by vico93** [ThirteenAG/Ultimate-ASI-Loader#53]
Seems like F1C is a DirectX 8 game (judging of the use of d3d8.dll in the very scarce mods available for this old game), while rf1 uses DirectX 9 (d3d9).

I can't test right now even because there is no ASI mods for these games, but if is theoretically possible to run ASI Loader with those i'm planning to let some folks know if they were interested in doing some fixes for those games (at least to make them run without issues on Windows 10+).

**Comment by ThirteenAG** [comment]
Better to check and see.

**Comment by vico93** [comment]
> Better to check and see.

So.. how can i test if ASI loader worked in a game with mo mods? is there any key/config that allows it do make a heartbeat to check if is loaded?

**Comment by ThirteenAG** [comment]
There's a MessageBox plugin for example: https://github.com/ThirteenAG/Ultimate-ASI-Loader/blob/master/source/demo_plugins/MessageBox.cpp

**Comment by vico93** [comment]
Thanks!
