### ISSUE TITLE
Not loading plugins in The Witcher: Enhanced Edition

### ISSUE THREAD

**Issue by ADawesomeguy** [ThirteenAG/Ultimate-ASI-Loader#55]
Hello!

I got this to work successfully for the Witcher 3 with a couple custom hooks, but I'm having a little trouble replicating that for the Witcher: Enhanced Edition. I've tries multiple x86 DLLs and I've monitored x32dbg. It seems to be loading the original DLL just fine but for some reason it isn't calling the function to load plugins from any directory. I've tried the main directory, the plugins directory, and the scripts directory. Please let me know if there's some mistake being made on my end or if any other information is needed.

Thanks!

![image](https://user-images.githubusercontent.com/67982792/182041546-88ef10ed-0b5b-4b7e-9d23-6d645f067d31.png)

P.S. the `Scripts` directory is built into the game, is it possible that the name is causing it to interfere somehow?

**Comment by ThirteenAG** [comment]
Try to change dontloadfromdllmain setting in the ini file. Plugins folder name doesn't matter, you can use 'plugins' instead of scripts.

**Comment by ADawesomeguy** [comment]
Alright, I'll give that a shot and get back to you. Thanks for the quick response!

**Comment by ADawesomeguy** [comment]
Hm, it doesn't seem to change anything. I tried values of both 1 and 0, in the plugins directory and outside for both the ASI file and `global.ini`.

**Comment by ThirteenAG** [comment]
Then it's probably not using that dll anymore? You can try using binkw32, and rename the original just in case.

**Comment by ADawesomeguy** [comment]
I've tried dinput8.dll, binkw32.dll, d3d9.dll, and winmm.dll. They all load in and also load their original versions from SysWOW64. Not sure why they aren't calling the LoadPlugins and related functions.

**Comment by ADawesomeguy** [comment]
Now I think I may have gotten it to work by adding `-A Win32` to the CMake command for my library. Waiting to close this really quick but I think this may have been an issue on my end.

**Comment by ADawesomeguy** [comment]
Yes it seems that may have been the problem the whole time. Sorry about that and thank you for your help!
