### ISSUE TITLE
Doesnt work on linux / proton / wine

### ISSUE THREAD

**Issue by LethalManBoob** [ThirteenAG/Ultimate-ASI-Loader#57]
:(

**Comment by ThirteenAG** [comment]
https://cookieplmonster.github.io/setup-instructions/#proton-wine

**Comment by LethalManBoob** [comment]
Sorry i mean that it crashes on boot. GTAV specificlly.

**Comment by Loominagit** [comment]
I think I've found a fix: https://github.com/ThirteenAG/Ultimate-ASI-Loader/issues/59#issuecomment-1266487412
