### ISSUE TITLE
dinput8.dll files give error on GTA 5 1.0.2699.0 version

### ISSUE THREAD

**Issue by shamim4s** [ThirteenAG/Ultimate-ASI-Loader#58]
Hi,
i have downloaded dinput8.dll from your last release. when i keep this file on GTA5 root directory its gave me these error. i have deleted asi files one by one from open camera, openiv.

even i have tried to compile your code same error.

but if i install openiv asi loader from OpenIV software its working.

actually i tried to load asi files from different loacation. thats why i tried your source code. 
can you help me to fix this ?
My GTA V version is 1.0.2699.0

Best regards
Shamim
![asi_error](https://user-images.githubusercontent.com/85999549/192426636-f90306b0-dd38-4f1f-a54c-3d7c1fa4b024.jpg)

**Comment by ThirteenAG** [comment]
What if you set this setting
https://github.com/ThirteenAG/Ultimate-ASI-Loader/blob/master/data/scripts/global.ini#L4
to 0?

**Comment by shamim4s** [comment]
> What if you set this setting https://github.com/ThirteenAG/Ultimate-ASI-Loader/blob/master/data/scripts/global.ini#L4 to 0?

when i keep this ini on scripts folder and open PlayGTAV.exe its just show black screen for few seconds and gone. nothing start.

**Comment by shamim4s** [comment]
still same problem in GTA 5 . i have downloaded your new version. but its gives error 
![err](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/85999549/10fd7f62-1529-4d9e-80e8-be8c7e63a2f4)

i have tried DontLoadFromDllMain=0 this also

**Comment by ThirteenAG** [comment]
I don't think GTA5 can work with universal asi loader, given there's drm, anticheat and I don't know what else. GTA5 specific asi loaders likely patch that out to work.

**Comment by MrFoxPro** [comment]
> I don't think GTA5 can work with universal asi loader, given there's drm, anticheat and I don't know what else. GTA5 specific asi loaders likely patch that out to work.

Hello, I'm wondering if you was able to make it work, because I saw following lines:

https://github.com/ThirteenAG/Ultimate-ASI-Loader/blob/f999fe976ddc5b3cf185506c628584ae8b56e490/source/dllmain.cpp#L2540-L2545
