### ISSUE TITLE
[Metal Gear Rising: Revengeance] Error 126

### ISSUE THREAD

**Issue by Frouk3** [ThirteenAG/Ultimate-ASI-Loader#60]
I made a cheat, but for others when injecting giving error 126
I saw that game need to be putted into another folder, not in Program Files (also, is that a solution for this error?)

**Comment by ThirteenAG** [comment]
> This can also happen when you're trying to load a DLL and that in turn needs another DLL which cannot be not found.

Either you didn't use static linking, didn't compile in release or something else.

**Comment by Frouk3** [comment]
> > This can also happen when you're trying to load a DLL and that in turn needs another DLL which cannot be not found.
> 
> Either you didn't use static linking, didn't compile in release or something else.

I'm sure it compiled in release and it doesn't need other dll to load, cheat is running on my PC, but for others error still appears, also about static linking, how to enable it in Visual Studio
Cheat is having .asi extension but not dll

**Comment by Frouk3** [comment]
accidently closed

**Comment by ThirteenAG** [comment]
![](https://user-images.githubusercontent.com/25625456/198375598-4638d2e0-49a6-41e5-a94c-deee4b1145d8.png)

**Comment by Frouk3** [comment]
now there's [LNK2001](https://learn.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2001?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(LNK2001)%26rd%3Dtrue&view=msvc-170)

**Comment by ThirteenAG** [comment]
https://stackoverflow.com/questions/60069081/what-is-libcpmtd-lib-for

**Comment by Frouk3** [comment]
> https://stackoverflow.com/questions/60069081/what-is-libcpmtd-lib-for

Yes i was there, and fixed, but i'm also in confuse from decompiled asi since i made specific functions for each feature instead

**Comment by Frouk3** [comment]
and yes it still doesn't load for others

**Comment by ThirteenAG** [comment]
I don't know, provide a project at least.

**Comment by Frouk3** [comment]
https://github.com/Frouk3/mgrCheat

**Comment by Frouk3** [comment]
> I don't know, provide a project at least.

also .asi is injected but doesn't show window no matter how you try, it won't open, also i have a project and wrote already the link to it
