### ISSUE TITLE
Too many cooks (Reshade, Resorep, 3dMigito)

### ISSUE THREAD

**Issue by DeathWrench** [ThirteenAG/Ultimate-ASI-Loader#61]
There's this cool [.asi script posted up for Black Flag](https://www.nexusmods.com/assassinscreedivblackflag/mods/371/) that uses this. Unfortunately this game has many mods that use [3DMigito](https://github.com/bo3b/3Dmigoto/releases) and [Resorep](https://www.undertow.club/downloads/resorep.1254/), seeing as it's getting old too it gains plenty of benefits from using [Reshade ](https://reshade.me/) with it. A while ago I found out you can rename .dll's to .asi and the loader should load them though this seems to have it's limits. I'm not sure how the naming works either.  I'm wondering if there is a way to make ASI loader load dll's inside of a specified folder like plugins. Or perhaps alternatively something in place to force load after dll's to avoid conflicts, I can use all 3 (Reshade, Resorep, and 3dMigito) but the .asi does not load when I try using this as well. 

Here is some more information about installing all 3.
Reshade files:
- dxgi.dll
- Reshade.ini

3DMigito files:
- d3dcompiler_46.dll
- ori_d3d11.dll (renamed from d3d11.dll in order to work with Resorep)
- d3dx.ini

Resorep files: 
- d3d11.dll (renamed from dx11_proxy32.dll)
- [dllsettings.ini](https://cdn.discordapp.com/attachments/515842332201975821/1056242082953576518/dllsettings.ini) (this file doesn't generate unless resorep.jar is ran)

**Comment by c22hk** [comment]
where to downlload Resorep.jar ?????//pls
