### ISSUE TITLE
Crashes on Dying Light 2

### ISSUE THREAD

**Issue by EricPlayZ** [ThirteenAG/Ultimate-ASI-Loader#65]
When using the x64 version of this ASI loader on Dying Light 2, it sort of works. It injects fine, it injects my mods, but the game crashes after a few seconds. Is this some kind of protection from the game? Even without any mods, just having the ASI loader present in the game directory makes the game crash. I tried all stubs, dinput8.dll seems to load later, at the start of the game's intro and then crashes, version.dll seems to load instantly at the splash screen of the game but also crashes right after.
![devenv_DCwHdLJ4ni](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/24963708/1282769b-b69b-468b-8414-44171a8d8e51)

Here is a crash dump generated by the ASI loader: https://drive.google.com/file/d/1grO2zWuxJTRt7SgX5AHR59WUEtwWNB0d/view?usp=sharing
It looks like Epic Games' overlay might be the issue according to the dump... It tries to write something to address 0000000000000000?
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/24963708/3047b6b9-343f-4764-b771-3f0c9d04f8b5)
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/24963708/37b217e4-e4c7-4afd-b2ae-01ba263a95b5)
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/24963708/af2b90c4-dc2f-43e2-8988-a5a47d39087a)

**Comment by ThirteenAG** [comment]
Can you try to launch without an overlay? But it could be all of those things you mentioned, hard to tell without looking into it.

**Comment by EricPlayZ** [comment]
I removed every overlay dll I could find per what I found on google (Steam's overlay and Epic Games' overlay were both injecting) and it still crashes, so it's not because of that. I've never analyzed dumps before, so I don't know what any of this means :D I'm assuming `engine_x64_rwdi!IKTools::HelperDebugDrawBox+0x542f` is causing the crash? In which case this would be a specific game issue...

![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/24963708/178abeae-b214-4edb-8f94-2223c2cd4c0e)
https://drive.google.com/file/d/18mk0s5pKaj7G4gTxtIwCj2DeDdt2NyXv/view?usp=sharing

**Comment by ThirteenAG** [comment]
If crash spot changes every time, it could be indeed an anti-cheat, or drm.

**Comment by EricPlayZ** [comment]
I've tried checking the functions from the stack trace but I understand nothing lol, all I see is some vectors and function calls that are uninitialized data basically and I can't see anything useful...

![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/24963708/f6ef371f-1988-4013-827c-2bf08849c34e)
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/24963708/1d0e30b3-15fe-420d-bfce-665916fb7959)

**Comment by EricPlayZ** [comment]
Manually injecting the dll using Xenos in an existing process seems to work fine, but injecting it using Manual Launch which detects the game process and immediately injects also causes the game to crash...
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/24963708/dcb94b0d-442d-4eeb-8073-1d41d6c33db3)

**Comment by EricPlayZ** [comment]
Turns out it had to do with my code... I wasn't null checking the pointer address that I was searching for :D Sorry for wasting your time... Should be more careful with debugging next time!

![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/24963708/c4c00559-63ac-4d9a-884a-de4095aefbdc)
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/24963708/672343fd-042a-4610-863c-4e449dac604e)

**Comment by EricPlayZ** [comment]
Nevermind, that was the cause for crashing when injecting too early :D This ASI loader still causes a crash no matter what (without the DLL as well, forgot about that).

**Comment by EricPlayZ** [comment]
Works fine as version.dll, dinput8.dll causes the crash! Issue fixed, sorry for the trouble again.
