### ISSUE TITLE
Old builds are removed

### ISSUE THREAD

**Issue by classc7601** [ThirteenAG/Ultimate-ASI-Loader#69]
He removed the old builds as they were compatible with Windows XP. What a miserable person. 
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/96195759/f7f72a65-0302-40bd-b9e4-6309a28e5cb0)

**Comment by ThirteenAG** [comment]
No builds of this were ever compatible with windows xp, get your facts straight.
