### ISSUE TITLE
Support .dll file extension

### ISSUE THREAD

**Issue by blackwind** [ThirteenAG/Ultimate-ASI-Loader#72]
Your excellent piece of work here works with all the .dll mods I've tried so far, but requires me to rename them to .asi for no particular reason other than "GTA used that extension once upon a time, so, let's go with that". But this is supposed to be a universal loader for any game. Why not load .dlls as well, at least from the `plugins` folder?

**Comment by ThirteenAG** [comment]
Because I can have additional dlls in plugins folder or elsewhere, that don't need to be loaded, or supposed to be loaded conditionally by an asi plugin. It's by design. Another reason - when you put mods to root dir, much easier to differentiate between native game dlls and plugins.

**Comment by blackwind** [comment]
100%, shouldn't be loading .dlls from the root folder, and it sounds like you have your reasons for the limitations of the other folders. Can I suggest a third folder, then, that loads only .dlls? Of all the tools for various games that do the same basic job, they all do it worse than yours in one way or another. This should (and could) be the one loader to rule them all, but you're largely confining yourself to the GTA niche with this artificial limitation that's useful for but the tiniest portion of users. Food for thought.
