### ISSUE TITLE
[Metal Gear Rising: Revengeance] Error: 225

### ISSUE THREAD

**Issue by AmogusEnjoyer69** [ThirteenAG/Ultimate-ASI-Loader#76]
When I try to load a ASI file to my game it just says "unable to load playable sam.ASI error: 225" what am I supposed to do?

**Comment by ThirteenAG** [comment]
ERROR_VIRUS_INFECTED

    225 (0xE1)

    Operation did not complete successfully because the file contains a virus or potentially unwanted software.

**Comment by AmogusEnjoyer69** [comment]
Is there a way to fix it or something? Because it works for others and it worked fine when I first opened it. But after that it started to give 225 error

**Comment by ThirteenAG** [comment]
Try to open properties of the file you're trying to load, there's sometimes a button to unblock, or check in windows defender.

**Comment by AmogusEnjoyer69** [comment]
Both didn't worked and yes I unblocked it correctly

**Comment by ThirteenAG** [comment]
Nothing I can do on my end.

**Comment by AmogusEnjoyer69** [comment]
Eh, thanks for helping.
