### ISSUE TITLE
RDR2's support

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/Ultimate-ASI-Loader#77]
Is this ASI Loader actually compatible with RDR2? I do have ScriptHook installed, however ASI's do not load at all.
I would like using this instead of the one bundled with ScriptHook since with this I can actually organize ASI plugins into their own plugins folder, instead of keeping them in the root.
Far as I know, this one works with GTAV so I wouldn't think RDR2 would have any need for other dependencies...

**Comment by ThirteenAG** [comment]
Added compatibility with existing GTAV/RDR2 asi loaders in v6.6, apparently UAL was loading plugins too early, causing some unintended errors.

**Comment by RecklessGlue540** [comment]
Nice, but how can plugins be loaded from the plugins folder? They don't seem to load on RDR2 at least. Kinda makes this useless...

**Comment by ThirteenAG** [comment]
https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/demo-plugins/MessageBox-x64.zip

Put to plugins folder, if message box shows, then it's not my problem.
