### ISSUE TITLE
Speed Mod related to ASI Loader doesnt work anymore. Any help is appriciated!

### ISSUE THREAD

**Issue by Pyr0blad3** [ThirteenAG/Ultimate-ASI-Loader#78]
Hello dead ThirteenAG / LionAG,

I know its not really related to the ASI Loader itself, but I think your mod: https://www.nexusmods.com/baldursgate3/mods/1536?tab=description&BH=1
stoped working as BG3 updated.

Could you update the mod as many wait for that, if you wont already work on it, OR upload the sourceCode of the .dll mod to a github repository and link it to the mod page, because this mod is very much needed for many players to play through the game again as it sames so much time!

Also with the sourceCode availlible it could be reprocuded in case you dont want to work on it / update it any further.

Sorry if I mistook you as a person or anything like that, BUT thanks for any help or updates on this if possible, cheers!

**Comment by ThirteenAG** [comment]
That is not my mod, you will have to contact the author. It is unlikely that asi loader is the issue here, perhaps the asi needs to be updated to work with newest game version?

**Comment by Pyr0blad3** [comment]
i just know that the ASI loader is included in the mod so i thought you made the mod. sorry in that case all this was my misunderstanding.

may i still ask you a question? how would i edit a .dll file, or do i really need the sourceCode to create a new .dll File. I tried to edit the mod myself but i didnt have any luck. i got VS and all that and i am kinda into programming but not mod making, so i have no clue how to edit this file. i only had access to the ressources of the .dll file containing a binary set and some file information, but no "code" or anything like that.

if you have no clue, still thanks for replying, cheers!

**Comment by ThirteenAG** [comment]
You need source code, yes.

**Comment by Pyr0blad3** [comment]
but yeah maybe the loader need to be updated to the newest version, idk if the loader need such things?
the error log of the mod stats: The mod was designed for different game version.

------------------------------------------
oh you replied fastly. yeah in that case the only one right now who can update the mod probably is the mod maker himself. do you know LionAG123 by any chance?

thanks again.

**Comment by ThirteenAG** [comment]
> but yeah maybe the loader need to be updated to the newest version, idk if the loader need such things?
No, it's rarely needed.

> do you know LionAG123 by any chance?
No.

**Comment by Pyr0blad3** [comment]
okay still a big thanks for giving me the info and talking to me. hope you have a good day, cheers! sorry for opening the issue...
