### ISSUE TITLE
Gamepass Starfield crash on launch with "this Library isn't supported" error message 

### ISSUE THREAD

**Issue by ASuicidalLobster** [ThirteenAG/Ultimate-ASI-Loader#79]
Help

**Comment by ThirteenAG** [comment]
Which library?

**Comment by PiqueLaLune** [comment]
Starfield Game pass édition le 20/11/2023 => mise a jour 1.8.86.0

Ça ne fonctionne plus (mods no work) :(

ASI dll modé "bink2w64.dll" (avant mise a jours) 343 ko
ASI "bink2w64.dll" (après mise a jours) 412 ko => Starfield se lance sans mods...

Si on re utilise le ASI dll modé  (de ThirteenAG Ultimate-ASI-Loader) => Starfild ne se lance pas...

--------------------------------------------------------Translate FR-> EN-----------------------------------------------------------------------------

Starfield Game pass edition 11/20/2023 => update 1.8.86.0

It doesn't work anymore (mods no work) :(

ASI dll moded "bink2w64.dll" (before update) 343 kb
ASI "bink2w64.dll" (after update) 412 kb => Starfield launches without mods...

If we use the modded ASI dll again (from ThirteenAG Ultimate-ASI-Loader) => Starfild does not launch...

**Comment by ASuicidalLobster** [comment]
> Which library?

Unsure, that's all it says

**Comment by ThirteenAG** [comment]
You need to rename **original** bink2w64.dll to bink2w64Hooked.dll, only after that install asi loader.

**Comment by MightionNY** [comment]
This happens on the Steam version, too, when I try to launch with SFSE_loader (updated for 1.8.86); redid achievement enabler, no good.

**Comment by ASuicidalLobster** [comment]
> You need to rename **original** bink2w64.dll to bink2w64Hooked.dll, only after that install asi loader.

![IMG_20231122_213541471_HDR](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/151529011/bc1e8822-8e5b-441f-a0aa-3743d0b6bdf1)
![IMG_20231122_213624419_HDR](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/151529011/6e75accc-0e1e-419d-9b31-856dd1b0e8de)
I don't know what I'm doing wrong.

**Comment by ThirteenAG** [comment]
My guess is bink2w64Hooked.dll is also an asi loader, so you're loading the same dll twice. bink2w64Hooked.dll should be original dll.

**Comment by ASuicidalLobster** [comment]
Yep, I'm an idiot, I didn't notice the original bink2w64.dll in the files, sorry.

**Comment by ASuicidalLobster** [comment]
(this is the fix for anyone having the problem I had)
There is already a file in the Starfield root folder. Don't worry you can get it back. (but it might mess with some of your mods) delete the 2 bink2w64.dll files and right click your game in either steam or Xbox. for steam you then go down to properties, to the installed files tab, and hit "Verify integrity of game files" for Xbox, you go down to the "Manage" tab, to files and down at the bottom is the verify and repair button. go to the Starfield root folder, (where Starfield.exe is) and rename "bink2w64.dll" to "bink2w64Hooked.dll" and then add the bink2w64.dll from here to your Starfield root folder.
And you should be good to go.
