### ISSUE TITLE
dsound.dll causes SH2 to hang on launch

### ISSUE THREAD

**Issue by Aero52** [ThirteenAG/Ultimate-ASI-Loader#8]
The latest version of UAL does not work when renamed to dsound.dll for SH2. A previous version of UAL from last year _does_ work, and it can be downloaded here:  https://mega.nz/#!ApYjgRbT!A5HEZLcalxyzaPr-c-f9IQiHdRASBVSsbNwQsl2hr4A

I have tried ForceEntryPointHook, which made no difference at all.

> [GlobalSets]
LoadPlugins=1
LoadFromScriptsOnly=1
ForceEntryPointHook=1
UseD3D8to9=0

**Comment by ThirteenAG** [comment]
ForceEntryPointHook=1 is the default behaviour. ForceEntryPointHook=0 may fix it.

**Comment by Aero52** [comment]
Oops. Yeah, ForceEntryPointHook=0 made no difference.

**Comment by ThirteenAG** [comment]
So, sh2 imports dsound function by ordinal, that's why it doesn't work.
![](http://i.imgur.com/oTEzDmi.png)
I don't think I can fix it.

**Comment by ThirteenAG** [comment]
But, it's something I can fix within widescreen fix, if you'd like.

**Comment by Aero52** [comment]
Wait, so you _can_  fix it? But the solution won't be within UAL, but within the widescreen fix itself? If so, yes, that's perfectly fine.

**Comment by ThirteenAG** [comment]
Yes, old version of ual had ordinals, but now I only use them for xlive.dll. In widescreen fix I can simply patch an address of imported function, so imported by ordinal function will never be called and the proper one will.

**Comment by ThirteenAG** [comment]
Actually I changed my mind, ca you try this build and see if it works now?
[dsound.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/files/1104756/dsound.zip)

Use only with ForceEntryPointHook=1, ordinal fix will not work without it.

**Comment by jdkubiak** [comment]
> Actually I changed my mind, can you try this build and see if it works now?
> dsound.zip
> 
> Use only with ForceEntryPointHook=1, ordinal fix will not work without it.

For me, I get the following system errors: 

`The program can't start because (MSVCP140D.dll, VCRUNTIME140D.dll, ucrtbased.dll) is missing from your computer.`

Interestingly enough, in addition to the year-old UAL working consistently when being renamed to dsound.dll, it also does **not** create [the lighting bug](https://github.com/crosire/d3d8to9/issues/24#issue-231129795) when using UseD3D8to9=1.

**Comment by ThirteenAG** [comment]
>For me, I get the following system errors:

It's a debug build, you probably don't have visual studio installed, that's why it doesn't work. I can compile a release version if you want to test, but later.

>Interestingly enough, in addition to the year-old UAL working consistently when being renamed to dsound.dll, it also does not create the lighting bug when using UseD3D8to9=1.

Well, it has an old version of d3d8to9, so d3d8to9 updates must be causing this.

**Comment by jdkubiak** [comment]
> you probably don't have visual studio installed

That is correct, so I will take my leave of this conversation after this. :) 

> Well, it has an old version of d3d8to9, so d3d8to9 updates must be causing this.

That makes sense. I also just tried using ReShade's stand-alone d3d8.dll for this and is now producing the same lighting bug.

**Comment by Aero52** [comment]
@ThirteenAG Works for me.

@jdkubiak If you don't want to wait, you can use Visual Studio Community. All you need to install from that is "Desktop development with C++" to get it working.

**Comment by jdkubiak** [comment]
Thank you sir. I'll hold off and wait to give it a try on the average-user level.

**Comment by ThirteenAG** [comment]
https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/latest

**Comment by jdkubiak** [comment]
Thank you ThirteenAG. Has this change been reflected in the WSF package downloads as well?

**Comment by ThirteenAG** [comment]
No. That's what modupdater is for.
