### ISSUE TITLE
Starfield Game pass édition le 20/11/2023 => mise a jour 1.8.86.0 / ASI "bink2w64.dll" (after update) 412 kb / bink2w64.dll" (before update) 343 kb no work

### ISSUE THREAD

**Issue by PiqueLaLune** [ThirteenAG/Ultimate-ASI-Loader#80]
Starfield Game pass édition le 20/11/2023 => mise a jour 1.8.86.0

Ça ne fonctionne plus (mods no work) :(

ASI dll modé "bink2w64.dll" (avant mise a jours) 343 ko
ASI "bink2w64.dll" (après mise a jours) 412 ko => Starfield se lance sans mods...

Si on re utilise le ASI dll modé  (de ThirteenAG Ultimate-ASI-Loader) => Starfild ne se lance pas...

------------------------Translate FR-> EN----------------------------

Starfield Game pass edition 11/20/2023 => update 1.8.86.0

It doesn't work anymore (mods no work) :(

ASI dll moded "bink2w64.dll" (before update) 343 kb
ASI "bink2w64.dll" (after update) 412 kb => Starfield launches without mods...

If we use the modded ASI dll again (from ThirteenAG Ultimate-ASI-Loader) => Starfild does not launch...

**Comment by JonL98** [comment]
Be sure to download the latest "Plugins.txt Enabler". There was an update just today. I haven't had any issues with it so far.
https://www.nexusmods.com/starfield/mods/4157

**Comment by ThirteenAG** [comment]
You should rename original/updated bink2w64.dll to bink2w64Hooked.dll, and then place bink2w64.dll as asi loader. This error message only appears when asi loader is named as something else.

**Comment by ak4ge** [comment]
So i had the same issue today, after disabling mods one by one it turns out my acheivement enabler was the issue, i used this one https://www.nexusmods.com/starfield/mods/1402
After disabled the game starts & all other plugins are working.
