### ISSUE TITLE
Version 6.7.0 getting flagged by Windows Defender

### ISSUE THREAD

**Issue by Mystyle-48** [ThirteenAG/Ultimate-ASI-Loader#82]
The latest release, version 6.7.0, cannot be used on my machine without constantly getting flagged by Windows Defender.

I noticed that the 6.7.0 is missing all the version information compared to 6.6.0. Perhaps this is where the issue is stemming from?

<img width="272" alt="ASI1" src="https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/89315313/e16fc147-6c02-478b-9f10-8605b9b96ef7">

<img width="272" alt="ASI2" src="https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/89315313/3ecc481d-fa38-4f9c-9245-654e696a8854">

**Comment by ThirteenAG** [comment]
The one from releases has this, where did you get the one without?

**Comment by Mystyle-48** [comment]
I got it from the GitHub releases page. Looks like Defender was just instantly deleting the file as soon as I extracted it. I turned off real-time protection and the file details are all still there. 

I've extracted several previous releases and this appears to be the one Defender has a consistent problem with.

**Comment by ThirteenAG** [comment]
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/4904157/81f7c454-3d07-4788-8c1c-7942546f7ed6)

You can submit a false positive anyway here: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by Mystyle-48** [comment]
Done. I'll keep using 6.6.0 until there is a solution.

**Comment by ThirteenAG** [comment]
Can you give a direct link to the archive with dll without version info?

**Comment by Mystyle-48** [comment]
Version info wasn't the issue. It was just disappearing from the properties because Defender was deleting the file and file explorer was not refreshing in time to remove the file from the list. It's likely something else.

**Comment by ThirteenAG** [comment]
I see, must be the try/catch block I added that compiled into something detectable in another thing.

**Comment by Mystyle-48** [comment]
Yeah, Defender gets really picky with how stuff is loaded. Hopefully this false positive report goes through and clears it up.

**Comment by ThirteenAG** [comment]
I've submitted one too, just in case, but the website does not show the detection
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/4904157/174bf09d-3831-4078-b281-6df589ff7c20)

**Comment by Mystyle-48** [comment]
Interesting, my submission also says nothing was detected:

![IMG_1947](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/89315313/0b5ba3bb-e32d-49c8-8bd0-9f68c7f57cc1)

**Comment by Mystyle-48** [comment]
Final determination is still pending though so that could change.

**Comment by Mystyle-48** [comment]
Tried downloading 6.7.0 again with the latest Windows Defender intelligence updates and this issue no longer occurs. Thank you for the assistance.
