### ISSUE TITLE
Overload from folder feature not working

### ISSUE THREAD

**Issue by sjp760** [ThirteenAG/Ultimate-ASI-Loader#83]
I was trying to use the overload from folder feature from resident evil 4 but it was not working. I am using the [playstation button icons as a test from the re4 hd project](https://www.re4hd.com/?page_id=9322) which is under PLAYSTATION CONTROLLER UI PACK. The hd project is installed of course using the official method without using the update folder

This was my folder layout. The d3d9.dll and my update folder are the ones related to the asi loader. The dinput8.dll is the dll for re4_tweaks. Re4_tweaks loads properly.
`
bio4.exe  bio4.exe.bak  d3d9.dll dinput8.dll  dinput8.ini  dinput8.log  re4_tweaks  steam_api.dll  update
`

And this is the update folder. The folders other than BIO4 also exist outside of BIO4 in case of incorrect pathing.
`
BIO4  ImagePackHD  option  Ranking
`

I am using linux and proton. I put the wine dll overrides like this
`
WINEDLLOVERRIDES="dinput8,d3d9=n,b"  %command%
`

The prompts still show up as xbox icons in game.

I also did some testing in Metal Gear Solid 3 with the MGS HD Fix and the crouch walk mod. I installed both mods and replaced the asi loader they included with the one here (I'm pretty sure they use yours anyway but I wanted to update it). 

Instead of overwriting the files in the assets folder, I put it into update (the overload folder) and the crouch walk did not work but when I overwrote the files instead it did. I can confirm the ASIs are being loaded as MGS HD Fix produces a log and crouch walk works properly when the files are replaced.

Also one question. Does the overload feature with files that are not there. For example, if I put a Fallout new Vegas plugin in the update folder, should it be detected in the game?

**Comment by ThirteenAG** [comment]
Works fine for me on windows,
put BIO4 folder from archive into `Resident Evil 4\Bin32\update\BIO4`.
Used d3d9 asi loader as well. Not sure what could go wrong on linux. Send me you discord id so we could try to debug this, if you want.

![4](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/4904157/c850e5c6-a7c8-447e-b09b-326cffe7acc7)

> Also one question. Does the overload feature with files that are not there. For example, if I put a Fallout new Vegas plugin in the update folder, should it be detected in the game?

It should, but depends on what loads them. If they are loaded with another asi/dll, then [OverloadFromFolderDLL.asi](https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/demo-plugins/OverloadFromFolderDLL-Win32.zip) is also needed.

**Comment by ThirteenAG** [comment]
Nope.

**Comment by ThirteenAG** [comment]
https://github.com/ThirteenAG/Ultimate-ASI-Loader/blob/master/source/demo_plugins/OverloadFromFolderDLL.cpp

it's not needed for re4 though.

**Comment by ThirteenAG** [comment]
From what I can tell, the feature just doesn't work on linux.

**Comment by ThirteenAG** [comment]
I guess, I don't know how wine/proton works, but I'm pretty sure people were able to run fusion fix for gta iv on steam deck, and it uses overload functionality as well.

**Comment by ThirteenAG** [comment]
Required.

**Comment by ThirteenAG** [comment]
[d3d9.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/files/13946111/d3d9.zip)
Try this.

**Comment by ThirteenAG** [comment]
FolderExists function behaved differently on windows and on linux I suppose, I rewrote it to check absolute path using filesystem api. Basically on linux it didn't load anything because it considered update folder non existent.

**Comment by ThirteenAG** [comment]
None, I checked myself.
