### ISSUE TITLE
Issues with wndmode.ini

### ISSUE THREAD

**Issue by KirbyFan102** [ThirteenAG/Ultimate-ASI-Loader#85]
I'm trying to play the game Blast Thru, an old PC game. In order to fix slowdown issues that occur in modern Windows, I used a wndmode.ini file with these parameters:

[WINDOWMODE]
UseWindowMode=1
UseGDI=0
UseDirect3D=0
UseDirectInput=0
UseDirectDraw=1
UseDDrawColorEmulate=1
UseDDrawFlipBlt=0
UseDDrawColorConvert=1
UseDDrawPrimaryBlt=1
UseDDrawAutoBlt=0
UseDDrawEmulate=1
UseDDrawPrimaryLost=0
UseCursorMsg=0
UseCursorSet=0
UseCursorGet=0
UseSpeedHack=0
SpeedHackMultiple=5
UseBackgroundResize=0
UseForegroundControl=0
UseFGCGetActiveWindow=0
UseFGCGetForegroundWindow=0
UseFGCFixedWindowPosition=0
EnableExtraKey=0
ShowFps=0
UseCursorClip=0
UseBackgroundPriority=0
DDrawBltWait=-1
Border=0

However, though the speed issue is fixed, there's a problem: The mouse doesn't stay in the window. Instead, while the in-game mouse moves in tandem with the real mouse cursor, which flies off the screen and when I try clicking on anything, it instead clicks off of the window and out of the game. I can't even start the first level because of this.

**Comment by ThirteenAG** [comment]
That one provided 'as is', and not supported unfortunately.

**Comment by KirbyFan102** [comment]
What do you mean? Where does that file come from, then? Where can I find how to edit it properly?

**Comment by ThirteenAG** [comment]
I learned of it from [here](https://habr.com/ru/articles/51857/) more than 10 years ago, some kind of modified version of d3d windower tool I think. Probably I wouldn't include it to asi loader now, but for compatibility reasons it's still there.
