### ISSUE TITLE
D:PL "update" folder overloading doesn't work for bink videos

### ISSUE THREAD

**Issue by charlesthobe** [ThirteenAG/Ultimate-ASI-Loader#87]
At least in Driver: Parallel Lines, files in `update/FMV/` don't load while other files load fine.

**Comment by charlesthobe** [comment]
Not sure if it's worth noting but I tried the `binkw32.dll` version of the asi loader with renaming the original to `binkw32Hooked.dll` and with removing the original dll to no avail (they work but they don't fix this issue).

**Comment by ThirteenAG** [comment]
It needs https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/demo-plugins/OverloadFromFolderDLL-Win32.zip

Because it's binkw32.dll that loads them, not exe.

**Comment by charlesthobe** [comment]
It works, tysm
