### ISSUE TITLE
The Overloader does not work for the Yakuza Remastered Collection games

### ISSUE THREAD

**Issue by RecklessGlue540** [ThirteenAG/Ultimate-ASI-Loader#89]
Tested Yakuza 3 in depth, with a lot of different names for the ASI Loader, also tried using the OverloadFromFolder_x64 demo-plugin, nothing worked. 
Some mods I tried out were the most popular ones, namely the [4K Fonts mod](https://www.nexusmods.com/yakuza3remastered/mods/16), and the [Censorship Restoration Patch](https://www.nexusmods.com/yakuza3remastered/mods/5). They just don't take effect at all.

While I know that Ryu Mod Manager exists for these, I don't really like it. Not to mention, the latter mod absolutely requires replacing the original game's files, which I don't really wanna do anymore to be honest... The Overloader simply redirects paths so technically it should just work as if you were to replace the files manually, right?

**Comment by ThirteenAG** [comment]
Try again with v7.3.0.
