### ISSUE TITLE
(GTA:SA) GInput doesn't load on Ultimate ASI Loader, only compatible with Silent's ASI Loader.

### ISSUE THREAD

**Issue by jaigitrep159** [ThirteenAG/Ultimate-ASI-Loader#96]
From here: https://gtaforums.com/topic/562765-ginput/

It pops up that it doesn't load due to incompatibility???? really confusing. Any ways to fix this?

**Comment by jaigitrep159** [comment]
By the way, i'm using GTA SA: v1.0 US, having cleo, ultimate asi loader, and modloader with 40+ mods installed.

**Comment by ThirteenAG** [comment]
What incompatibility?

**Comment by jaigitrep159** [comment]
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/76834328/850c5fb0-2a0a-43a3-8b85-e6d2be483c12)
this.

**Comment by jaigitrep159** [comment]
i did everything for VC Runtime All In One from Github but this does nothing.

**Comment by jaigitrep159** [comment]
![image](https://github.com/ThirteenAG/Ultimate-ASI-Loader/assets/76834328/e4b06692-5934-49eb-b5f0-7f98a6253a27)
and plus i am using the latest version of Ultimate ASI Loader (7.2.0)

**Comment by ThirteenAG** [comment]
You're missing some dll then, you can use https://github.com/lucasg/Dependencies to find out which.

**Comment by jaigitrep159** [comment]
Okay so i just missing out on this, so this: https://www.microsoft.com/en-us/Download/confirmation.aspx?id=35 fixed the issue.

False report issue. Sorry about this. I am closing this issue now.
