### ISSUE TITLE
Starfield CTD with Access denied on bink2w64.dll 7.5.0

### ISSUE THREAD

**Issue by aggietallboy** [ThirteenAG/Ultimate-ASI-Loader#97]
Starfield version 1.12.30.0
bink2w64.dll, 411kb dated today after xbox reinstall.

Renamed to bink2w64Hooked.dll and then copied in new 7.5.0 (tested with 7.4.0 as well) ASI patched dll.

- did through vortex as well as manual test.
- disabled/purged all other mods to narrow it down.

When patched bink is present Windows 11 throws a Controlled Folder error, with starfield.exe blocked from making changes - however, starfield.exe cannot be whitelisted (permissions error on the executable), Crash 000005  (Access Denied) when launching.

Disabled/Removed the dll, and restored old, all worked properly (except, my FTTU .asi doesn't load)

**Comment by ThirteenAG** [comment]
Was bink2w64.dll updated? Can you upload it?

**Comment by aggietallboy** [comment]
Sure thing

________________________________

**Comment by aggietallboy** [comment]
https://www.dropbox.com/t/CNtz8Vv177siDZyV
[bink2w64.zip](https://github.com/user-attachments/files/15831711/bink2w64.zip)

**Comment by ThirteenAG** [comment]
I don't see any new exports, and I don't have the game. If you could upload a [crash dump](http://dk22pac.blogspot.com/2013/02/how-to-enable-crash-dumps-dmp-files.html), I can take a look at that.

**Comment by aggietallboy** [comment]
Will see if i can create it

________________________________

**Comment by aggietallboy** [comment]
[Starfield.exe.23820.zip](https://github.com/user-attachments/files/15831823/Starfield.exe.23820.zip)
Three most recent dumps

**Comment by ThirteenAG** [comment]
>	[Frames may be missing, no binary loaded for fttu.asi]		Annotated Frame
>	fttu.asi!00007ffba51f1490()	Unknown	Non-user code. No matching binary found.

That's asi crashing in all dumps, it's not compatible with the new game version. You should update the asi, asi loader works fine.

**Comment by aggietallboy** [comment]
You sir, are amazing, I really appreciate the amazingly fast response and analysis!!

________________________________
