### ISSUE TITLE
[Question] How to Choose load order?

### ISSUE THREAD

**Issue by shinra358** [ThirteenAG/Ultimate-ASI-Loader#98]
when placing 3 or more dll (turned asi's) into the loading folder, how do you tell this program to load them in a specific order?

**Comment by ThirteenAG** [comment]
There's no built in functionality for that. Usually it's not required to load plugins in specific order. Sometimes you can get away with renaming them and load in alphabetical order.
Or have first plugin as asi, and load others from that asi in the order you want.

**Comment by shinra358** [comment]
oh ok

**Comment by shinra358** [comment]
How would one solve the issue of umod when it doesnt have a dll to go into the folder and you have a chain of dlls that start in dx9 but end in dx12 or vulkan?

**Comment by ThirteenAG** [comment]
I don't understand.

**Comment by shinra358** [comment]
if a third party changes the game from dx9 to dx12/vulkan, how would one get Umod to work? Umod junctions to dx9 games. It doesnt have a dll to drop in the Asi loader folder. It doesnt seem to work if I point to the game that has been changed from dx9 to dx12/vulkan. Do you know of a technique or can you come up with something for asi loader to delay the dll folder so that Umod goes first, then the dll asi folder loads?

**Comment by ThirteenAG** [comment]
I don't think I can answer that. Asi loader has nothing to do with directx, and how other mods work depends entirely on them.

**Comment by shinra358** [comment]
i know it doesnt have anything to do with directx, but can't it delay loading the asi loader dll folder if you code it in?

**Comment by ThirteenAG** [comment]
I don't know what you mean by dll folder, dll loading order is determined by the application.

**Comment by shinra358** [comment]
your instructions say to make a plugins folder to put the dlls in. that is the dll folder. im not talking about loading order.
