### ISSUE TITLE
3 New Windowmode Options

### ISSUE THREAD

**Issue by shinra358** [ThirteenAG/Ultimate-ASI-Loader#99]
Can we get the options:

Start in Window Mode [start.windowed] = 0/1 (if you dont want to start in window mode but need hotkeys to go into window mode - different from existing option)

and 

window mode window size = x,y [window.size] (control size of window when using window mode - 'Quarter' would be an option also to auto scale to 1/4 of desktop resolution size)

and

Window mode hotkey [window.hotkey] = (keyboard combo to initiate window mode, do what you have to do, and then use combo to go back to game's own fs mode.)

**Comment by ThirteenAG** [comment]
Windowed mode is a legacy feature and not supported/maintained right now.
